Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -117,7 +117,8 @@ jobs:
         run: |
           ssh $DEPLOY_USER@$DEPLOY_SERVER "
             which node
-            which npm
+            pwd
+            whoami
           "
 
         
@@ -137,7 +138,8 @@ jobs:
             pkill -f 'node' || true &&
             /home/founder/.nvm/versions/node/v23.11.0/bin/npm install && 
             /home/founder/.nvm/versions/node/v23.11.0/bin/npx prisma generate && 
-            /home/founder/.nvm/versions/node/v23.11.0/bin/npm run start:prod & 
+            /home/founder/.nvm/versions/node/v23.11.0/bin/npm run start:prod || {
+               echo 'App failed to start';
+               exit 1;
+             }
             "
-        
-      
